apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  selector:
    app: phpmyadmin
  ports:
    - name: phpmyadmin
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
