apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
                - containerPort: 20
                - containerPort: 21
                - containerPort: 21100
                - containerPort: 21101
                - containerPort: 21102
                - containerPort: 21103
                - containerPort: 21104
        volumeMounts:
        - name: ftps
          mountPath: /var/lib/ftp
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: vsftpd-pv-claim
