apiVersion: v1
kind: PersistentVolume
metadata:
  name: vsftpd-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ftps"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsftpd-pv-claim
  labels:
    app: vsftpd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
